# Generated by Django 3.0.7 on 2020-06-23 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donos', '0002_auto_20200622_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='drive',
            name='orgID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='donos.Organization'),
            preserve_default=False,
        ),
    ]
