# Generated by Django 3.0.7 on 2020-06-23 01:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('donos', '0004_userdrives'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('code', models.UUIDField()),
                ('driveID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donos.Drive')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('driveID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donos.Drive')),
            ],
        ),
        migrations.CreateModel(
            name='DonationItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('donationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donos.Donation')),
            ],
        ),
    ]
